name = "yatrai-planner-worker"
main = "src/index.ts"
compatibility_date = "2026-01-17"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "RBAC_KV"
id = "a67eaa9f473e40d9b80f9959d922c8fd"
preview_id = "bd3c136f383b4f5e9c178ef97ccba2c9"

[env.preview]
name = "yatrai-planner-worker-preview"
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
  { binding = "RBAC_KV", id = "a67eaa9f473e40d9b80f9959d922c8fd", preview_id = "bd3c136f383b4f5e9c178ef97ccba2c9" }
]
